services:
  dashboard:
    image: us-central1-docker.pkg.dev/neat-airport-407301/lum-docker-images/lumino-dashboard:latest
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      - LUI_API_BASE_URL=${LUI_API_BASE_URL}
    extra_hosts:
      - "localhost:host-gateway"