services:
  dashboard:
    image: us-central1-docker.pkg.dev/neat-airport-407301/lum-docker-images/lumino-dashboard:latest
#    build: .
    command: yarn start
    volumes:
      - .logs:/project/.logs
    ports:
      - "3000:3000"
    environment:
      - LUI_ENV=${LUI_ENV:-local}
      - LUI_API_BASE_URL=${LUI_API_BASE_URL:-http://localhost:5100/v1}
    extra_hosts:
      - "localhost:host-gateway"